### ISSUE TITLE
#[serde(transparent)] on a struct with a Vec seems a little too transparent in quick-xml.

### ISSUE THREAD

**Issue by 8bittree** [tafia/quick-xml#216]
Applying the `#[serde(transparent)]` attribute on a struct whose only field is a `Vec` seems to remove one too many layers.

### Expected output
```xml
<vec><Element></Element><Element></Element>
```

### Actual output
```xml
<Element></Element><Element></Element>
```

### Code to demonstrate
(Includes a couple other formats for comparison. Note that the transparent json and sexp output only loses one layer of wrapping compared to the opaque versions.)
rustc version is 1.43.1. 

#### Cargo.toml
```toml
[package]
name = "serde-tests"
version = "0.1.0"
edition = "2018"

[dependencies]
quick-xml = {version = "^0.18.1", features = ["serialize"]}
serde = {version = "^1.0.111", features = ["derive"]}
serde_json = "1.0"
serde-lexpr = "0.1.0"
```

#### src/main.rs
```rust
use quick_xml;
use serde::{Deserialize, Serialize};
use serde_json;
use serde_lexpr;

#[derive(Debug, Deserialize, Serialize)]
struct Opaque {
    vec: Vec<Element>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(transparent)]
struct Transparent {
    vec: Vec<Element>,
}

#[derive(Debug, Deserialize, Serialize)]
struct Element {
    
}

fn main() {
    let o = Opaque { vec: vec![ Element {}, Element {} ] };
    let t = Transparent { vec: vec![ Element {}, Element {} ] };

    println!("Opaque xml: {:?}", quick_xml::se::to_string(&o).unwrap());
    println!("Transparent xml: {:?}", quick_xml::se::to_string(&t).unwrap());

    println!("");

    println!("Opaque json: {:?}", serde_json::to_string(&o).unwrap());
    println!("Transparent json: {:?}", serde_json::to_string(&t).unwrap());

    println!("");

    println!("Opaque sexp: {:?}", serde_lexpr::to_string(&o).unwrap());
    println!("Transparent sexp: {:?}", serde_lexpr::to_string(&t).unwrap());
}
```

### Notes
I came across this while trying to work with xml like [this](https://github.com/scottdraves/flam3/blob/master/test.flam3). Deserialization seems to work fine (at least for the simplified tests I've been running - haven't gotten around to adding all the attributes to the structs yet), but serialization has been problematic. I keep getting either one too many intermediate layers, or one too few as is the case here.
