### ISSUE TITLE
feature `serialization`: `#[serde(flatten)]` does not work for different types

### ISSUE THREAD

**Issue by jfrimmel** [tafia/quick-xml#286]
Hello, 
I encountered an unexpected behavior when using `#[serde(flatten)]` with this crate. See the example below.

# Reproduction
`Cargo.toml`:
```toml
[package]
name = "valgrind-xml"
version = "0.0.0"
edition = "2018"

[dependencies]
quick-xml = { version="0.22", features=["serialize"] }
serde = { version="1", features=["derive"] }
serde_json = "1"
```
`src/main.rs`:
```rust
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct S {
    name: String,
    #[serde(flatten)]
    resource: Resource,
}

#[derive(Debug, Deserialize)]
struct Resource {
    a: i32,
    b: u64,
}

// should have the same behavior as `S`, but everything is inlined
#[derive(Debug, Deserialize)]
struct S2 {
    name: String,
    a: i32,
    b: u64,    
}

fn main() {
    let r: Result<S, _> = quick_xml::de::from_str(r#"<root name="omg" a="-1" b="42"/>"#); // doesn't work
    dbg!(r);
    let s: S2 = quick_xml::de::from_str(r#"<root name="omg" a="-1" b="42"/>"#).unwrap(); // works
    dbg!(s);

    // serde_json as reference:
    let s: S = serde_json::de::from_str(r#"{ "name": "omg", "a": -1, "b": 42 }"#).unwrap(); // works
    dbg!(s);
    let s: S2 = serde_json::de::from_str(r#"{ "name": "omg", "a": -1, "b": 42 }"#).unwrap(); // works
    dbg!(s);
}
```
Output of `cargo run`:
```
[src/main.rs:25] r = Err(
    Custom(
        "invalid type: map, expected i32",
    ),
)
[src/main.rs:27] s = S2 {
    name: "omg",
    a: -1,
    b: 42,
}
[src/main.rs:29] s = S {
    name: "omg",
    resource: Resource {
        a: -1,
        b: 42,
    },
}
[src/main.rs:31] s = S2 {
    name: "omg",
    a: -1,
    b: 42,
}
```
