### ISSUE TITLE
unflatten not working

### ISSUE THREAD

**Issue by unshakable-horse** [tafia/quick-xml#406]
The code:
```rust
use serde::Deserialize;
use serde::Serialize;

fn main<>() {
    let s = r#"<root><first>value</first><second>value</second></root>"#;
    let r:Root = from_str(s).unwrap();
    println!("r = {:?}",&r);
}
#[derive(Deserialize,Serialize,Debug)]
#[serde(rename="root")]
struct Root {
    #[serde(rename = "$unflatten=first")]
    first: String,

    #[serde(rename = "$unflatten=second")]
    other_field: String,
}
```

The dependencies:
```toml
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.22", features = [ "serialize" ] }
```

but i get error :"thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("missing field `$unflatten=first`")', src/main.rs:10:30"
