### ISSUE TITLE
could not find `de` in `quick_xml`

### ISSUE THREAD

**Issue by valerius21** [tafia/quick-xml#506]
When trying to use the `quick_xml::de` space, the compiler throws an error that it cannot be resolved. Looking through the documentation and other errors I can't seem to find any solution. Any ideas on how to solve it? I don't know if it's a bug.

## Minimal Test Case

Repo https://github.com/valerius21/quick-xml-issue

```bash
$ git clone https://github.com/valerius21/quick-xml-issue.git
````

```rust
// main.rs

const URL: &str = "https://www.gesetze-im-internet.de/gii-toc.xml";

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let body = reqwest::get(URL).await?.text().await?;

    let res = quick_xml::de::from_str(&body);

    println!("{:#?}", res);

    Ok(())
}
```

```toml
# Cargo.toml

[package]
name = "test-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
quick-xml = "0.26.0"
serde = { version = "1.0.130", features = ["derive"] }
reqwest = "0.11.6"
tokio = { version = "1.12.0", features = ["full"] }
```
